name: Build Application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Add appsettings.json
      run: 'echo "$APPSETTINGS_JSON" > src/RecycleBin.Notes/appsettings.Production.json'
      shell: bash
      env:
        APPSETTINGS_JSON: ${{ secrets.APPSETTINGS_JSON }}
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Publish
      run: dotnet publish --configuration Release -o app --no-build
    - uses: actions/upload-artifact@v1
      if: success()
      with:
        name: app
        path: ./app/wwwroot
